### ISSUE TITLE
validate ethereum blockchain?

### ISSUE THREAD

**Issue by hems** [chainpoint/chainpoint-validate-js#2]
Is it on the roadmap?

This would be a good example of an ethereum proof, i guess ( :
````
{ anchors:
   [ { prefix: '5336BA7C',
       type: 'ETHData',
       sourceId: '0x794f8c80b760207534559e8235c98c9e29a9686594ac8b6d54c53d9bd708505a' } ],
  type: 'BTA-SHA256',
  targetHash: '520EFF4ABE6BBE32CF50EE9D0FDC16E28ACDDB45C7E2C5D5E808A79FDC364582',
  '@context': 'https://w3id.org/chainpoint/v2',
  merkleRoot: '520EFF4ABE6BBE32CF50EE9D0FDC16E28ACDDB45C7E2C5D5E808A79FDC364582',
  proof: [] 
}
````

**Comment by grempe** [comment]
Hi @hems,

The proof example you provided is a non-standard Chainpoint proof. I believe it might have been created by Stampery since the receipt `type` for the proof is `BTA-SHA256`. You can see the list of officially supported types for a Chainpoint v2 receipt on the website we created to document the standard.

http://www.chainpoint.org/

I would suggest reaching out to them for code that will allow you to verify custom proofs created by them. I'll close this issue. Please feel free to comment further if you think this is incorrect.

Cheers.

**Comment by hems** [comment]
As you can see on their documentation https://api.stampery.com they are printing 
````
"@context": "https://w3id.org/chainpoint/v2",
````
on their ethereum proof, so i assumed it worked. but now looking at the possible types on chainpoint website it seems that SHA256 isn't accepted as you said!

**Comment by grempe** [comment]
That's right @hems, I think they added their own type `BTA-SHA256` which is outside the spec. You'd have to ask them what their motivation was for choosing that instead of `ChainpointSHA256v2` which is in the spec and presumably does the same thing. So their Chainpoint proof is not technically compliant with the `https://w3id.org/chainpoint/v2` definition which has a JSON-LD context that looks like:

```
// 20170330123628
// https://www.chainpoint.org/contexts/chainpoint-v2.jsonld

{
  "@context": {
    "id": "@id",
    "type": "@type",
    "cp": "https://w3id.org/chainpoint#",
    "ChainpointSHA224v2": "cp:ChainpointSHA224v2",
    "ChainpointSHA256v2": "cp:ChainpointSHA256v2",
    "ChainpointSHA384v2": "cp:ChainpointSHA384v2",
    "ChainpointSHA512v2": "cp:ChainpointSHA512v2",
    "ChainpointSHA3-224v2": "cp:ChainpointSHA3-224v2",
    "ChainpointSHA3-256v2": "cp:ChainpointSHA3-256v2",
    "ChainpointSHA3-384v2": "cp:ChainpointSHA3-384v2",
    "ChainpointSHA3-512v2": "cp:ChainpointSHA3-512v2",
    "BTCOpReturn": "cp:BTCOpReturn",
    "ETHData": "cp:ETHData",
    "targetHash": "cp:targetHash",
    "merkleRoot": "cp:merkleRoot",
    "proof": {
      "@id": "cp:proof",
      "@container": "@list"
    },
    "anchors": {
      "@id": "cp:anchors",
      "@container": "@list"
    },
    "sourceId": "cp:sourceId",
    "right": "cp:right",
    "left": "cp:left"
  }
}
```

Please also note, we are actively working on a major update to the Chainpoint specification which will be announced shortly. You can keep an eye on https://www.chainpoint.org for info.

**Comment by hems** [comment]
@grempe thank you a lot for your quick replies and helpful information provided, i'm already in touch with them.

**Comment by grempe** [comment]
👍 Happy to help. Let me know what you find out.
